### ISSUE TITLE
Goblirangs Angry Bee on flying enemies 

### ISSUE THREAD

**Issue by sunnydaler** [ironhidegames/issues-kr4#169]
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/43391939/94429666-9f737700-01cd-11eb-8ac1-4ef902fa2c8f.gif)

It doesn't deal damage to flying enemies.

**Comment by cigumo** [comment]
there is a flag in the config to allow flying enemies. 
should I turn it on or was it on purpose @thehalfleprechaun ?

**Comment by cigumo** [comment]
approved

**Comment by cigumo** [comment]
fixed in 1.9.9.10

**Comment by Mmlh1** [comment]
This is still a problem sadly, maybe it got accidentally reverted?
